// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarisApi.DbContexts;

#nullable disable

namespace StarisApi.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20240421004247_AddOnCharactersNewColumns")]
    partial class AddOnCharactersNewColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("StarisApi.Models.Characters.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthYear")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Mass")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
