// <auto-generated />
using System;
using May.The.Fourth.Backend.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace may.the.fourth.backend.data.migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20240425203548_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.MovieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Director");

                    b.Property<int?>("Episode")
                        .HasColumnType("INT")
                        .HasColumnName("Episode");

                    b.Property<string>("OpeningCrawl")
                        .HasColumnType("TEXT")
                        .HasColumnName("OpeningCrawl");

                    b.Property<string>("Producer")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Producer");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("DATE")
                        .HasColumnName("ReleaseDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "George Lucas",
                            Episode = 4,
                            OpeningCrawl = "",
                            Producer = "Gary Kurtz, Rick McCallum",
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A New Hope"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Irvin Kershner",
                            Episode = 5,
                            OpeningCrawl = "",
                            Producer = "Gary Kurtz, Rick McCallum",
                            ReleaseDate = new DateTime(1980, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Richard Marquand",
                            Episode = 6,
                            OpeningCrawl = "",
                            Producer = "Howard G. Kazanjian, George Lucas, Rick McCallum",
                            ReleaseDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Return of the Jedi"
                        },
                        new
                        {
                            Id = 4,
                            Director = "George Lucas",
                            Episode = 1,
                            OpeningCrawl = "",
                            Producer = "Rick McCallum",
                            ReleaseDate = new DateTime(1999, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Phantom Menace"
                        },
                        new
                        {
                            Id = 5,
                            Director = "George Lucas",
                            Episode = 2,
                            OpeningCrawl = "",
                            Producer = "Rick McCallum",
                            ReleaseDate = new DateTime(2002, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Attack of the Clones"
                        },
                        new
                        {
                            Id = 6,
                            Director = "George Lucas",
                            Episode = 3,
                            OpeningCrawl = "",
                            Producer = "Rick McCallum",
                            ReleaseDate = new DateTime(2005, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Revenge of the Sith"
                        });
                });

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.StarshipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoCapacity")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CargoCapacity");

                    b.Property<string>("Class")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Class");

                    b.Property<string>("Consumables")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Consumables");

                    b.Property<string>("CostInCredits")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CostInCredits");

                    b.Property<string>("Crew")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Crew");

                    b.Property<string>("HyperdriveRating")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("HyperdriveRating");

                    b.Property<string>("Length")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Length");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Manufacturer");

                    b.Property<string>("MaxSpeed")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("MaxSpeed");

                    b.Property<string>("Mglt")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Mglt");

                    b.Property<string>("Model")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Name");

                    b.Property<string>("Passengers")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Passengers");

                    b.HasKey("Id");

                    b.ToTable("Starships");
                });
#pragma warning restore 612, 618
        }
    }
}
