// <auto-generated />
using System;
using May.The.Fourth.Backend.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace may.the.fourth.backend.data.migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20240426001545_CreateCharacterTable")]
    partial class CreateCharacterTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.CharacterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("CharacterID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthYear")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("BirthYear");

                    b.Property<string>("EyeColor")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("EyeColor");

                    b.Property<string>("Gender")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Gender");

                    b.Property<string>("HairColor")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("HairColor");

                    b.Property<string>("Height")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Name");

                    b.Property<int?>("PlanetID")
                        .HasColumnType("INT")
                        .HasColumnName("PlanetID");

                    b.Property<string>("SkinColor")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("SkinColor");

                    b.Property<string>("Weight")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = "19BBY",
                            EyeColor = "blue",
                            Gender = "male",
                            HairColor = "blond",
                            Height = "172",
                            Name = "Luke Skywalker",
                            PlanetID = 1,
                            SkinColor = "fair",
                            Weight = "77"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = "112BBY",
                            EyeColor = "yellow",
                            Gender = "n/a",
                            HairColor = "n/a",
                            Height = "167",
                            Name = "C-3PO",
                            PlanetID = 1,
                            SkinColor = "gold",
                            Weight = "75"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = "33BBY",
                            EyeColor = "red",
                            Gender = "n/a",
                            HairColor = "n/a",
                            Height = "96",
                            Name = "R2-D2",
                            PlanetID = 8,
                            SkinColor = "white, blue",
                            Weight = "32"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = "41.9BBY",
                            EyeColor = "yellow",
                            Gender = "male",
                            HairColor = "none",
                            Height = "202",
                            Name = "Darth Vader",
                            PlanetID = 1,
                            SkinColor = "white",
                            Weight = "136"
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = "19BBY",
                            EyeColor = "brown",
                            Gender = "female",
                            HairColor = "brown",
                            Height = "150",
                            Name = "Leia Organa",
                            PlanetID = 2,
                            SkinColor = "light",
                            Weight = "49"
                        },
                        new
                        {
                            Id = 6,
                            BirthYear = "52BBY",
                            EyeColor = "blue",
                            Gender = "male",
                            HairColor = "brown, grey",
                            Height = "178",
                            Name = "Owen Lars",
                            PlanetID = 1,
                            SkinColor = "light",
                            Weight = "120"
                        },
                        new
                        {
                            Id = 7,
                            BirthYear = "47BBY",
                            EyeColor = "blue",
                            Gender = "female",
                            HairColor = "brown",
                            Height = "165",
                            Name = "Beru Whitesun lars",
                            PlanetID = 1,
                            SkinColor = "light",
                            Weight = "75"
                        },
                        new
                        {
                            Id = 8,
                            BirthYear = "unknown",
                            EyeColor = "red",
                            Gender = "n/a",
                            HairColor = "n/a",
                            Height = "97",
                            Name = "R5-D4",
                            PlanetID = 1,
                            SkinColor = "white, red",
                            Weight = "32"
                        },
                        new
                        {
                            Id = 9,
                            BirthYear = "24BBY",
                            EyeColor = "brown",
                            Gender = "male",
                            HairColor = "black",
                            Height = "183",
                            Name = "Biggs Darklighter",
                            PlanetID = 1,
                            SkinColor = "light",
                            Weight = "84"
                        },
                        new
                        {
                            Id = 10,
                            BirthYear = "57BBY",
                            EyeColor = "blue-gray",
                            Gender = "male",
                            HairColor = "auburn, white",
                            Height = "182",
                            Name = "Obi-Wan Kenobi",
                            PlanetID = 20,
                            SkinColor = "fair",
                            Weight = "77"
                        },
                        new
                        {
                            Id = 11,
                            BirthYear = "41.9BBY",
                            EyeColor = "blue",
                            Gender = "male",
                            HairColor = "blond",
                            Height = "188",
                            Name = "Anakin Skywalker",
                            PlanetID = 1,
                            SkinColor = "fair",
                            Weight = "84"
                        });
                });

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.FilmeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("FilmeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("DATE")
                        .HasColumnName("DataLancamento");

                    b.Property<string>("Diretor")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Diretor");

                    b.Property<int?>("Episodio")
                        .HasColumnType("INT")
                        .HasColumnName("Episodio");

                    b.Property<string>("Produtor")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Produtor");

                    b.Property<string>("TextoAbertura")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("TextoAbertura");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataLancamento = new DateTime(2028, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diretor = "Jana Doe",
                            Episodio = 10,
                            Produtor = "Leo Smith",
                            TextoAbertura = "After the fall of the Empire, the galaxy face",
                            Titulo = "The Rise of the Jedi"
                        },
                        new
                        {
                            Id = 2,
                            Titulo = "The Battle of the Stars"
                        },
                        new
                        {
                            Id = 3,
                            Titulo = "Return of the Light"
                        },
                        new
                        {
                            Id = 4,
                            Titulo = "Warriors of the Shadow Realm"
                        },
                        new
                        {
                            Id = 5,
                            Titulo = "The Galactic Quest"
                        },
                        new
                        {
                            Id = 6,
                            Titulo = "Rise of the Planetara"
                        },
                        new
                        {
                            Id = 7,
                            Titulo = "Echoes of the Stars"
                        },
                        new
                        {
                            Id = 8,
                            Titulo = "The Return of the Voyager"
                        },
                        new
                        {
                            Id = 9,
                            Titulo = "Voyager's Endgame"
                        },
                        new
                        {
                            Id = 10,
                            Titulo = "Galactic Odyssey"
                        },
                        new
                        {
                            Id = 11,
                            Titulo = "The Edge of the Universe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
