// <auto-generated />
using System;
using May.The.Fourth.Backend.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace may.the.fourth.backend.data.migrations
{
    [DbContext(typeof(StarWarsContext))]
    partial class StarWarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.MovieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Director");

                    b.Property<int?>("Episode")
                        .HasColumnType("INT")
                        .HasColumnName("Episode");

                    b.Property<string>("OpeningCrawl")
                        .HasColumnType("TEXT")
                        .HasColumnName("OpeningCrawl");

                    b.Property<string>("Producer")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Producer");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("DATE")
                        .HasColumnName("ReleaseDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "George Lucas",
                            Episode = 4,
                            OpeningCrawl = "",
                            Producer = "Gary Kurtz, Rick McCallum",
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A New Hope"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Irvin Kershner",
                            Episode = 5,
                            OpeningCrawl = "",
                            Producer = "Gary Kurtz, Rick McCallum",
                            ReleaseDate = new DateTime(1980, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Richard Marquand",
                            Episode = 6,
                            OpeningCrawl = "",
                            Producer = "Howard G. Kazanjian, George Lucas, Rick McCallum",
                            ReleaseDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Return of the Jedi"
                        },
                        new
                        {
                            Id = 4,
                            Director = "George Lucas",
                            Episode = 1,
                            OpeningCrawl = "",
                            Producer = "Rick McCallum",
                            ReleaseDate = new DateTime(1999, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Phantom Menace"
                        },
                        new
                        {
                            Id = 5,
                            Director = "George Lucas",
                            Episode = 2,
                            OpeningCrawl = "",
                            Producer = "Rick McCallum",
                            ReleaseDate = new DateTime(2002, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Attack of the Clones"
                        },
                        new
                        {
                            Id = 6,
                            Director = "George Lucas",
                            Episode = 3,
                            OpeningCrawl = "",
                            Producer = "Rick McCallum",
                            ReleaseDate = new DateTime(2005, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Revenge of the Sith"
                        });
                });

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.StarshipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoCapacity")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CargoCapacity");

                    b.Property<string>("Class")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Class");

                    b.Property<string>("Consumables")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Consumables");

                    b.Property<string>("CostInCredits")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CostInCredits");

                    b.Property<string>("Crew")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Crew");

                    b.Property<string>("HyperdriveRating")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("HyperdriveRating");

                    b.Property<string>("Length")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Length");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Manufacturer");

                    b.Property<string>("MaxSpeed")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("MaxSpeed");

                    b.Property<string>("Mglt")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Mglt");

                    b.Property<string>("Model")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Name");

                    b.Property<string>("Passengers")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Passengers");

                    b.HasKey("Id");

                    b.ToTable("Starships");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CargoCapacity = "3000000",
                            Class = "corvette",
                            Consumables = "1 year",
                            CostInCredits = "3500000",
                            Crew = "30-165",
                            HyperdriveRating = "2.0",
                            Length = "150",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxSpeed = "950",
                            Mglt = "60",
                            Model = "CR90 corvette",
                            Name = "CR90 corvette",
                            Passengers = "600"
                        },
                        new
                        {
                            Id = 3,
                            CargoCapacity = "36000000",
                            Class = "Star Destroyer",
                            Consumables = "2 years",
                            CostInCredits = "150000000",
                            Crew = "47,060",
                            HyperdriveRating = "2.0",
                            Length = "1,600",
                            Manufacturer = "Kuat Drive Yards",
                            MaxSpeed = "975",
                            Mglt = "60",
                            Model = "Imperial I-class Star Destroyer",
                            Name = "Star Destroyer",
                            Passengers = "n/a"
                        },
                        new
                        {
                            Id = 5,
                            CargoCapacity = "180000",
                            Class = "landing craft",
                            Consumables = "1 month",
                            CostInCredits = "240000",
                            Crew = "5",
                            HyperdriveRating = "1.0",
                            Length = "38",
                            Manufacturer = "Sienar Fleet Systems, Cyngus Spaceworks",
                            MaxSpeed = "1000",
                            Mglt = "70",
                            Model = "Sentinel-class landing craft",
                            Name = "Sentinel-class landing craft",
                            Passengers = "75"
                        },
                        new
                        {
                            Id = 9,
                            CargoCapacity = "1000000000000",
                            Class = "Deep Space Mobile Battlestation",
                            Consumables = "3 years",
                            CostInCredits = "1000000000000",
                            Crew = "342,953",
                            HyperdriveRating = "4.0",
                            Length = "120000",
                            Manufacturer = "Imperial Department of Military Research, Sienar Fleet Systems",
                            MaxSpeed = "n/a",
                            Mglt = "10",
                            Model = "DS-1 Orbital Battle Station",
                            Name = "Death Star",
                            Passengers = "843,342"
                        },
                        new
                        {
                            Id = 10,
                            CargoCapacity = "100000",
                            Class = "Light freighter",
                            Consumables = "2 months",
                            CostInCredits = "100000",
                            Crew = "4",
                            HyperdriveRating = "0.5",
                            Length = "34.37",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxSpeed = "1050",
                            Mglt = "75",
                            Model = "YT-1300 light freighter",
                            Name = "Millennium Falcon",
                            Passengers = "6"
                        },
                        new
                        {
                            Id = 11,
                            CargoCapacity = "110",
                            Class = "assault starfighter",
                            Consumables = "1 week",
                            CostInCredits = "134999",
                            Crew = "2",
                            HyperdriveRating = "1.0",
                            Length = "14",
                            Manufacturer = "Koensayr Manufacturing",
                            MaxSpeed = "1000km",
                            Mglt = "80",
                            Model = "BTL Y-wing",
                            Name = "Y-wing",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 12,
                            CargoCapacity = "110",
                            Class = "Starfighter",
                            Consumables = "1 week",
                            CostInCredits = "149999",
                            Crew = "1",
                            HyperdriveRating = "1.0",
                            Length = "12.5",
                            Manufacturer = "Incom Corporation",
                            MaxSpeed = "1050",
                            Mglt = "100",
                            Model = "T-65 X-wing",
                            Name = "X-wing",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 13,
                            CargoCapacity = "150",
                            Class = "Starfighter",
                            Consumables = "5 days",
                            CostInCredits = "unknown",
                            Crew = "1",
                            HyperdriveRating = "1.0",
                            Length = "9.2",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxSpeed = "1200",
                            Mglt = "105",
                            Model = "Twin Ion Engine Advanced x1",
                            Name = "TIE Advanced x1",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 15,
                            CargoCapacity = "250000000",
                            Class = "Star dreadnought",
                            Consumables = "6 years",
                            CostInCredits = "1143350000",
                            Crew = "279,144",
                            HyperdriveRating = "2.0",
                            Length = "19000",
                            Manufacturer = "Kuat Drive Yards, Fondor Shipyards",
                            MaxSpeed = "n/a",
                            Mglt = "40",
                            Model = "Executor-class star dreadnought",
                            Name = "Executor",
                            Passengers = "38000"
                        },
                        new
                        {
                            Id = 17,
                            CargoCapacity = "19000000",
                            Class = "Medium transport",
                            Consumables = "6 months",
                            CostInCredits = "unknown",
                            Crew = "6",
                            HyperdriveRating = "4.0",
                            Length = "90",
                            Manufacturer = "Gallofree Yards, Inc.",
                            MaxSpeed = "650",
                            Mglt = "20",
                            Model = "GR-75 medium transport",
                            Name = "Rebel transport",
                            Passengers = "90"
                        },
                        new
                        {
                            Id = 21,
                            CargoCapacity = "70000",
                            Class = "Patrol craft",
                            Consumables = "1 month",
                            CostInCredits = "unknown",
                            Crew = "1",
                            HyperdriveRating = "3.0",
                            Length = "21.5",
                            Manufacturer = "Kuat Systems Engineering",
                            MaxSpeed = "1000",
                            Mglt = "70",
                            Model = "Firespray-31-class patrol and attack",
                            Name = "Slave 1",
                            Passengers = "6"
                        },
                        new
                        {
                            Id = 22,
                            CargoCapacity = "80000",
                            Class = "Armed government transport",
                            Consumables = "2 months",
                            CostInCredits = "240000",
                            Crew = "6",
                            HyperdriveRating = "1.0",
                            Length = "20",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxSpeed = "850",
                            Mglt = "50",
                            Model = "Lambda-class T-4a shuttle",
                            Name = "Imperial shuttle",
                            Passengers = "20"
                        },
                        new
                        {
                            Id = 23,
                            CargoCapacity = "6000000",
                            Class = "Escort ship",
                            Consumables = "2 years",
                            CostInCredits = "8500000",
                            Crew = "854",
                            HyperdriveRating = "2.0",
                            Length = "300",
                            Manufacturer = "Kuat Drive Yards",
                            MaxSpeed = "800",
                            Mglt = "40",
                            Model = "EF76 Nebulon-B escort frigate",
                            Name = "EF76 Nebulon-B escort frigate",
                            Passengers = "75"
                        },
                        new
                        {
                            Id = 27,
                            CargoCapacity = "unknown",
                            Class = "Star Cruiser",
                            Consumables = "2 years",
                            CostInCredits = "104000000",
                            Crew = "5400",
                            HyperdriveRating = "1.0",
                            Length = "1200",
                            Manufacturer = "Mon Calamari shipyards",
                            MaxSpeed = "n/a",
                            Mglt = "60",
                            Model = "MC80 Liberty type Star Cruiser",
                            Name = "Calamari Cruiser",
                            Passengers = "1200"
                        },
                        new
                        {
                            Id = 28,
                            CargoCapacity = "40",
                            Class = "Starfighter",
                            Consumables = "1 week",
                            CostInCredits = "175000",
                            Crew = "1",
                            HyperdriveRating = "1.0",
                            Length = "9.6",
                            Manufacturer = "Alliance Underground Engineering, Incom Corporation",
                            MaxSpeed = "1300",
                            Mglt = "120",
                            Model = "RZ-1 A-wing Interceptor",
                            Name = "A-wing",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 29,
                            CargoCapacity = "45",
                            Class = "Assault Starfighter",
                            Consumables = "1 week",
                            CostInCredits = "220000",
                            Crew = "1",
                            HyperdriveRating = "2.0",
                            Length = "16.9",
                            Manufacturer = "Slayn & Korpil",
                            MaxSpeed = "950",
                            Mglt = "91",
                            Model = "A/SF-01 B-wing starfighter",
                            Name = "B-wing",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 31,
                            CargoCapacity = "unknown",
                            Class = "Space cruiser",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Crew = "9",
                            HyperdriveRating = "2.0",
                            Length = "115",
                            Manufacturer = "Corellian Engineering Corporation",
                            MaxSpeed = "900",
                            Mglt = "unknown",
                            Model = "Consular-class cruiser",
                            Name = "Republic Cruiser",
                            Passengers = "16"
                        },
                        new
                        {
                            Id = 32,
                            CargoCapacity = "4000000000",
                            Class = "Droid control ship",
                            Consumables = "500 days",
                            CostInCredits = "unknown",
                            Crew = "175",
                            HyperdriveRating = "2.0",
                            Length = "3170",
                            Manufacturer = "Hoersch-Kessel Drive, Inc.",
                            MaxSpeed = "n/a",
                            Mglt = "unknown",
                            Model = "Lucrehulk-class Droid Control Ship",
                            Name = "Droid control ship",
                            Passengers = "139000"
                        },
                        new
                        {
                            Id = 39,
                            CargoCapacity = "65",
                            Class = "Starfighter",
                            Consumables = "7 days",
                            CostInCredits = "200000",
                            Crew = "1",
                            HyperdriveRating = "1.0",
                            Length = "11",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps",
                            MaxSpeed = "1100",
                            Mglt = "unknown",
                            Model = "N-1 starfighter",
                            Name = "Naboo fighter",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 40,
                            CargoCapacity = "unknown",
                            Class = "yacht",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Crew = "8",
                            HyperdriveRating = "1.8",
                            Length = "76",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
                            MaxSpeed = "920",
                            Mglt = "unknown",
                            Model = "J-type 327 Nubian royal starship",
                            Name = "Naboo Royal Starship",
                            Passengers = "unknown"
                        },
                        new
                        {
                            Id = 41,
                            CargoCapacity = "2500000",
                            Class = "Space Transport",
                            Consumables = "30 days",
                            CostInCredits = "55000000",
                            Crew = "1",
                            HyperdriveRating = "1.5",
                            Length = "26.5",
                            Manufacturer = "Republic Sienar Systems",
                            MaxSpeed = "1180",
                            Mglt = "unknown",
                            Model = "Star Courier",
                            Name = "Scimitar",
                            Passengers = "6"
                        },
                        new
                        {
                            Id = 43,
                            CargoCapacity = "unknown",
                            Class = "Diplomatic barge",
                            Consumables = "1 year",
                            CostInCredits = "2000000",
                            Crew = "5",
                            HyperdriveRating = "0.7",
                            Length = "39",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
                            MaxSpeed = "2000",
                            Mglt = "unknown",
                            Model = "J-type diplomatic barge",
                            Name = "J-type diplomatic barge",
                            Passengers = "10"
                        },
                        new
                        {
                            Id = 47,
                            CargoCapacity = "unknown",
                            Class = "freighter",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Crew = "unknown",
                            HyperdriveRating = "unknown",
                            Length = "390",
                            Manufacturer = "Botajef Shipyards",
                            MaxSpeed = "unknown",
                            Mglt = "unknown",
                            Model = "Botajef AA-9 Freighter-Liner",
                            Name = "AA-9 Coruscant freighter",
                            Passengers = "30000"
                        },
                        new
                        {
                            Id = 48,
                            CargoCapacity = "60",
                            Class = "Starfighter",
                            Consumables = "7 days",
                            CostInCredits = "180000",
                            Crew = "1",
                            HyperdriveRating = "1.0",
                            Length = "8",
                            Manufacturer = "Kuat Systems Engineering",
                            MaxSpeed = "1150",
                            Mglt = "unknown",
                            Model = "Delta-7 Aethersprite-class interceptor",
                            Name = "Jedi starfighter",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 49,
                            CargoCapacity = "unknown",
                            Class = "yacht",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Crew = "4",
                            HyperdriveRating = "0.9",
                            Length = "47.9",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps",
                            MaxSpeed = "8000",
                            Mglt = "unknown",
                            Model = "H-type Nubian yacht",
                            Name = "H-type Nubian yacht",
                            Passengers = "unknown"
                        },
                        new
                        {
                            Id = 52,
                            CargoCapacity = "11250000",
                            Class = "assault ship",
                            Consumables = "2 years",
                            CostInCredits = "unknown",
                            Crew = "700",
                            HyperdriveRating = "0.6",
                            Length = "752",
                            Manufacturer = "Rothana Heavy Engineering",
                            MaxSpeed = "unknown",
                            Mglt = "unknown",
                            Model = "Acclamator I-class assault ship",
                            Name = "Republic Assault ship",
                            Passengers = "16000"
                        },
                        new
                        {
                            Id = 58,
                            CargoCapacity = "240",
                            Class = "yacht",
                            Consumables = "7 days",
                            CostInCredits = "35700",
                            Crew = "3",
                            HyperdriveRating = "1.5",
                            Length = "15.2",
                            Manufacturer = "Huppla Pasa Tisc Shipwrights Collective",
                            MaxSpeed = "1600",
                            Mglt = "unknown",
                            Model = "Punworcca 116-class interstellar sloop",
                            Name = "Solar Sailer",
                            Passengers = "11"
                        },
                        new
                        {
                            Id = 59,
                            CargoCapacity = "50000000",
                            Class = "capital ship",
                            Consumables = "4 years",
                            CostInCredits = "125000000",
                            Crew = "600",
                            HyperdriveRating = "1.5",
                            Length = "1088",
                            Manufacturer = "Rendili StarDrive, Free Dac Volunteers Engineering corps.",
                            MaxSpeed = "1050",
                            Mglt = "unknown",
                            Model = "Providence-class carrier/destroyer",
                            Name = "Trade Federation cruiser",
                            Passengers = "48247"
                        },
                        new
                        {
                            Id = 61,
                            CargoCapacity = "50000",
                            Class = "transport",
                            Consumables = "56 days",
                            CostInCredits = "1000000",
                            Crew = "5",
                            HyperdriveRating = "1.0",
                            Length = "18.5",
                            Manufacturer = "Cygnus Spaceworks",
                            MaxSpeed = "2000",
                            Mglt = "unknown",
                            Model = "Theta-class T-2c shuttle",
                            Name = "Theta-class T-2c shuttle",
                            Passengers = "16"
                        },
                        new
                        {
                            Id = 63,
                            CargoCapacity = "20000000",
                            Class = "star destroyer",
                            Consumables = "2 years",
                            CostInCredits = "59000000",
                            Crew = "7400",
                            HyperdriveRating = "1.0",
                            Length = "1137",
                            Manufacturer = "Kuat Drive Yards, Allanteen Six shipyards",
                            MaxSpeed = "975",
                            Mglt = "unknown",
                            Model = "Senator-class Star Destroyer",
                            Name = "Republic attack cruiser",
                            Passengers = "2000"
                        },
                        new
                        {
                            Id = 64,
                            CargoCapacity = "unknown",
                            Class = "yacht",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Crew = "3",
                            HyperdriveRating = "0.5",
                            Length = "29.2",
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated",
                            MaxSpeed = "1050",
                            Mglt = "unknown",
                            Model = "J-type star skiff",
                            Name = "Naboo star skiff",
                            Passengers = "3"
                        },
                        new
                        {
                            Id = 65,
                            CargoCapacity = "60",
                            Class = "starfighter",
                            Consumables = "2 days",
                            CostInCredits = "320000",
                            Crew = "1",
                            HyperdriveRating = "1.0",
                            Length = "5.47",
                            Manufacturer = "Kuat Systems Engineering",
                            MaxSpeed = "1500",
                            Mglt = "unknown",
                            Model = "Eta-2 Actis-class light interceptor",
                            Name = "Jedi Interceptor",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 66,
                            CargoCapacity = "110",
                            Class = "starfighter",
                            Consumables = "5 days",
                            CostInCredits = "155000",
                            Crew = "3",
                            HyperdriveRating = "1.0",
                            Length = "14.5",
                            Manufacturer = "Incom Corporation, Subpro Corporation",
                            MaxSpeed = "1000",
                            Mglt = "100",
                            Model = "Aggressive Reconnaissance-170 starfighte",
                            Name = "arc-170",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 68,
                            CargoCapacity = "40000000",
                            Class = "cruiser",
                            Consumables = "2 years",
                            CostInCredits = "57000000",
                            Crew = "200",
                            HyperdriveRating = "1.0",
                            Length = "825",
                            Manufacturer = "Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries",
                            MaxSpeed = "unknown",
                            Mglt = "unknown",
                            Model = "Munificent-class star frigate",
                            Name = "Banking clan frigte",
                            Passengers = "unknown"
                        },
                        new
                        {
                            Id = 74,
                            CargoCapacity = "140",
                            Class = "starfighter",
                            Consumables = "7 days",
                            CostInCredits = "168000",
                            Crew = "1",
                            HyperdriveRating = "6",
                            Length = "6.71",
                            Manufacturer = "Feethan Ottraw Scalable Assemblies",
                            MaxSpeed = "1100",
                            Mglt = "unknown",
                            Model = "Belbullab-22 starfighter",
                            Name = "Belbullab-22 starfighter",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 75,
                            CargoCapacity = "60",
                            Class = "starfighter",
                            Consumables = "15 hours",
                            CostInCredits = "102500",
                            Crew = "1",
                            HyperdriveRating = "1.0",
                            Length = "7.9",
                            Manufacturer = "Kuat Systems Engineering",
                            MaxSpeed = "1050",
                            Mglt = "unknown",
                            Model = "Alpha-3 Nimbus-class V-wing starfighter",
                            Name = "V-wing",
                            Passengers = "0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
